### ISSUE TITLE
Question about self-hosting the web version of StegCloak

### ISSUE THREAD

**Issue by whalehub** [KuroLabs/stegcloak#10]
Just wanted to ask if it's possible to host your own version of https://stegcloak.surge.sh/ with the npm package `stegcloak` and if so, how?

**Comment by AK5123** [comment]
@whalehub It is possible, one way would be to export **stegcloak.min.js** from **dist** directory and include it within your HTML code through a script tag and use it. Else you could use libraries like browserify ([reference](https://www.bart.com.hk/use-npm-browser-js/)) to do the same.

**Comment by kepebi** [comment]
@AK5123 It is completely unclear how to do this. Can you explain in more detail?

**Comment by oneofthehorses** [comment]
> Just wanted to ask if it's possible to host your own version of https://stegcloak.surge.sh/ with the npm package `stegcloak` and if so, how?

Had you found any sucess?? Also wonder how to self host it too
