### ISSUE TITLE
Problems with transparent strings visible on the Windows operating system

### ISSUE THREAD

**Issue by hmmhmmhm** [KuroLabs/stegcloak#12]
Hello. First of all, thank you for making a nice library.
And i found one interesting thing about using this library.

I own Android, Mac and iOS and have tested the equipment.
The tests on my equipment were successful,
but some of the transparent letters were visible to window users.

![스크린샷 2020-06-17 오후 5 22 20](https://user-images.githubusercontent.com/38493722/84874154-2be6a780-b0bf-11ea-9a80-ff4a10dad68a.png)

I sent the message below to my friends who can see the transparent string,
and I received the answer below.

![KakaoTalk_Photo_2020-06-17-17-22-32](https://user-images.githubusercontent.com/38493722/84874433-8aac2100-b0bf-11ea-8437-08273807174f.png)

so... it's looks like a U+2060 has can be seeing when the
user are have some windows machines.

I recommend deleting U+2060 to improve the completeness of this library.

**Comment by mohanpierce99** [comment]
Thanks for testing this out, Really appreciate the find. Can you point me to which app/messenger you were using in windows ?

**Comment by JyothishmathiCV** [comment]
Can you please tell which app was used and also which version of Windows OS was used?

**Comment by hmmhmmhm** [comment]
ohh.. wait i'll tell the my frields hold on..!

**Comment by hmmhmmhm** [comment]
The exact details are as follows:
- Windows 10 Pro 2004
- Windows 10 Home 1903

When I sent the same message, most of my friends said they couldn't see it, but some Korean Windows 10 OS users could see the string.

I now suspect that this phenomenon occurs in the CJK (Chinese Japan Korea) font family. If we find a clear way to reproduce it, we'll notify you again.

**Comment by mohanpierce99** [comment]
I think its the font lemme check on this

**Comment by hmmhmmhm** [comment]
@mohanpierce99 I'm sorry. I didn't understand. Does that mean I have to check what the default font is?

**Comment by mohanpierce99** [comment]
No, so maybe test it out by pasting in your notepad in windows. Check if it gets rendered wierdly there

**Comment by mohanpierce99** [comment]
If it gets rendered wierdly there we can conclude it was because of the os else Kakaotalk's font is messing it up

**Comment by hmmhmmhm** [comment]
hmm.. Okay, I'll check it out.

**Comment by hmmhmmhm** [comment]
<img width="445" alt="스크린샷 2020-06-17 오후 6 14 15" src="https://user-images.githubusercontent.com/38493722/84879597-6273f080-b0c6-11ea-97fc-c068b28f9d48.png">

ooooh I also succeeded in checking the issue in my parreels.
i'm using of windows 10 korea edition.

i tried chrome github -> notepad (copy and paste)

**Comment by mohanpierce99** [comment]
We should go ahead and remove the character @JyothishmathiCV

**Comment by hmmhmmhm** [comment]
<img width="457" alt="스크린샷 2020-06-17 오후 6 17 19" src="https://user-images.githubusercontent.com/38493722/84879955-e29a5600-b0c6-11ea-89fa-78110c4e3629.png">
= korean font (font name: 맑은 고딕)


<img width="452" alt="스크린샷 2020-06-17 오후 6 17 52" src="https://user-images.githubusercontent.com/38493722/84880196-3016c300-b0c7-11ea-957f-5577c9b0a6ac.png">
= arial font

Clearly, the way it is seems like in CJK's national OS is different. The only way to reproduce this is to install a Korean language pack on Windows 10 and see it for yourself.

**Comment by mohanpierce99** [comment]
Yup ! Already on it well remove the character

**Comment by JyothishmathiCV** [comment]
PR for the bug is up and will be rolled as a new release soon! Thanks again. I am closing this issue.
