### ISSUE TITLE
Repeat Word

### ISSUE THREAD

**Issue by nguyenpm2** [KuroLabs/stegcloak#16]
![1](https://user-images.githubusercontent.com/45281730/85195797-adc51380-b2ff-11ea-8282-47fcb8dc0e1f.PNG)

**Comment by AK5123** [comment]
Thanks @nguyenpm2. We will look into it asap.

**Comment by mohanpierce99** [comment]
@nguyenpm2  Can you help us replicate the issue. The secret, password, and cover cause its working on our test cases

**Comment by AK5123** [comment]
@mohanpierce99 I've tested the website, it seems to work fine. We have to verify the module end. I believe it is due to our recent push which dealt with randomised insertion.

**Comment by JyothishmathiCV** [comment]
The bug is detected and fixed. It was due to the recent push regarding random insertions. @AK5123 please make the changes in the website.
