### ISSUE TITLE
Flow diagram

### ISSUE THREAD

**Issue by yezz123** [KuroLabs/stegcloak#22]
Hello! 👋
I guess this diagram you use is from Telegram security diagram flow 
![FlowDiagram](https://user-images.githubusercontent.com/52716203/92144965-68e54f00-ee0f-11ea-9108-f82d3f04575a.png)

And i ask if its the same here and thank you!

**Comment by mohanpierce99** [comment]
No it isn't, this flowchart was constructed by us from scratch in draw.io and telegram doesn't have ZWC, password derivation function or anything of this type in their flowchart from what I've seen in google images. I don't know how you find them similar , can you link up the flowchart you compared it to, it would help a lot to resolve your question.

**Comment by mohanpierce99** [comment]
Closing this now
