### ISSUE TITLE
extra characters in encrypted msg

### ISSUE THREAD

**Issue by rnyPlanet** [KuroLabs/stegcloak#24]
I use Windows 10. and I have additional characters after the encrypting, after which it is impossible to decode.
```
stegcloak hide --config to_send.json
```
![Screenshot_2](https://user-images.githubusercontent.com/33624178/95548595-17cc0a80-0a0e-11eb-9da0-e12914b962e7.png)
![Screenshot_3](https://user-images.githubusercontent.com/33624178/95548610-1f8baf00-0a0e-11eb-8434-c397696a2138.png)

**Comment by mohanpierce99** [comment]
What is the editor you use here?

**Comment by rnyPlanet** [comment]
pycharm. additional characters are characters that are in encrypted_msg between fff and fff

**Comment by mohanpierce99** [comment]
Ah! Those aren't additional characters. Try. Copy pasting the whole thing in  a notepad or a Google doc anywhere else. It would actually be invisible

**Comment by mohanpierce99** [comment]
Those characters are the invisible characters which hold your encrypted secret

**Comment by rnyPlanet** [comment]
Oh, really!) Thank you! I just forgot to test the decrypt) But there is one more error, after receiving msg from the social network, the msg cannot be decoded.
![Screenshot_4](https://user-images.githubusercontent.com/33624178/95549594-3cc17d00-0a10-11eb-9ef2-58cbb8acc31b.png)

for example, the following text. maybe the social network has forbidden to encode?

**Comment by mohanpierce99** [comment]
Can you paste the encrypted text, the url of social network site you tried it on as well. It should work everywhere except certain editors like vim,pycharm in this case.

**Comment by rnyPlanet** [comment]
Encrypted text: test ⁢‍⁢⁡‌⁡⁢⁤⁤⁤‌⁢‌‌⁡‍⁡‍⁡⁢‌⁡⁣‍‌‍⁢‌⁢‍⁢⁣⁡⁢⁣⁡‌⁢⁢‍⁢⁢⁢⁢⁢⁤⁢⁣‌‍‌⁡‍‌⁡⁢⁢‌test
Password: 1
Url of social network: https://web.telegram.org/#/login

**Comment by mohanpierce99** [comment]
https://res.cloudinary.com/dqmbs2chk/video/upload/v1602226585/WhatsApp_Video_2020-10-09_at_12.23.26_PM_hathgj.mp4

It works in web.telegram. Tested in both cli and the website of stegcloak

**Comment by rnyPlanet** [comment]
I believe that telethon is not sent correctly. and so thanks for the help)
