### ISSUE TITLE
Broken decipher

### ISSUE THREAD

**Issue by RAYDENFilipp** [KuroLabs/stegcloak#25]
Given the secret "Hello" and a password 123 and a text tO cloak into as 'Ggygvh ⁢‍⁢‌⁡⁢⁡‌⁣⁣‍⁤⁢⁢⁢‌‍⁢⁡‌⁢‍⁢⁡‍⁡⁣⁡⁢‌‍‌⁢⁢‌⁢⁤⁢⁤⁢‌⁢‌‌‌⁢⁡‌hhhggcgh higfgh', the decipher of it yields broken result of the secret being 'HelbW'
![Screenshot_20201101-124442](https://user-images.githubusercontent.com/24476415/97800750-72890880-1c40-11eb-86c4-b35b10dca96e.png)

**Comment by mohanpierce99** [comment]
> Given the secret "Hello" and a password 123 and a text tO cloak into as 'Ggygvh ⁢‍⁢‌⁡⁢⁡‌⁣⁣‍⁤⁢⁢⁢‌‍⁢⁡‌⁢‍⁢⁡‍⁡⁣⁡⁢‌‍‌⁢⁢‌⁢⁤⁢⁤⁢‌⁢‌‌‌⁢⁡‌hhhggcgh higfgh', the decipher of it yields broken result of the secret being 'HelbW'

Copy pasting 'Ggygvh ⁢‍⁢‌⁡⁢⁡‌⁣⁣‍⁤⁢⁢⁢‌‍⁢⁡‌⁢‍⁢⁡‍⁡⁣⁡⁢‌‍‌⁢⁢‌⁢⁤⁢⁤⁢‌⁢‌‌‌⁢⁡‌hhhggcgh higfgh' in stegcloak with password 123 yields Hello correctly here. Make sure you didnt stegcloak an already stegcloaked cover message

**Comment by mohanpierce99** [comment]
Closing this issue for now, recheck and please reopen if you have problems with Stegcloak again 👍

**Comment by RAYDENFilipp** [comment]
> Closing this issue for now, recheck and please reopen if you have problems with Stegcloak again 👍

indeed that could have been an issue. Rechecked, everything is OK.
