### ISSUE TITLE
php/js version is possible?

### ISSUE THREAD

**Issue by Leproide** [KuroLabs/stegcloak#28]
Hi!
Exist a version of this epic tool can run without npm?

**Comment by mohanpierce99** [comment]
There's a bundled version of stegcloak right here https://github.com/KuroLabs/stegcloak/tree/master/dist

**Comment by Leproide** [comment]
Yea i see but if i open the index obtain a blank page

**Comment by AK5123** [comment]
> Yea i see but if i open the index obtain a blank page

Can you be more specific??

**Comment by mohanpierce99** [comment]
Okay, the index.html in the first folder is not supposed to be opened it just has the stegcloak.min.js script ready for you to use. Now you can use the stegcloak API https://github.com/KuroLabs/stegcloak#api-usage

const stegcloak = new Stegcloak(true,false)

stegcloak.hide or stegcloak.reveal

Use the API however you want, but you can take the stegcloak.min.js and use it wherever you want in your website.

This is a the demo site which you see for stegcloak written in react - https://github.com/AK5123/StegCloak_DemoSite

**Comment by PeterH220** [comment]
> Okay, the index.html in the first folder is not supposed to be opened it just has the stegcloak.min.js script ready for you to use. Now you can use the stegcloak API https://github.com/KuroLabs/stegcloak#api-usage
> 
> const stegcloak = new Stegcloak(true,false)
> 
> stegcloak.hide or stegcloak.reveal
> 
> Use the API however you want, but you can take the stegcloak.min.js and use it wherever you want in your website.
> 
> This is a the demo site which you see for stegcloak written in react - https://github.com/AK5123/StegCloak_DemoSite

Please make normal, regular demo for people like me who are not familiar with coding, api usage, or React. Just a standard click-to-open index.html where your excellent script works without a need for react.
