### ISSUE TITLE
Changing the ZWC amount.

### ISSUE THREAD

**Issue by boredgame137** [KuroLabs/stegcloak#32]
Trying to change the ZWCs and the amount of them used to three on this line here in stegcloak.js.

const zwc = ["‌", "‍", "​"]; (200c, 200d, 200b)

It looks like the shrink and expand function expect 5 and 6 characters so is there an easy way to limit it to user three or two? Thank you.

**Comment by AK5123** [comment]
@boredgame137 It is possible to restrict the number of ZWCs. However this modification is not a direct fix, the algorithm should be modified appropriately.

**Comment by boredgame137** [comment]
Thank you for your time and suggestion!
