### ISSUE TITLE
Problem with Hide stegcloak

### ISSUE THREAD

**Issue by zentkhv** [KuroLabs/stegcloak#33]
When I try to get the content from the out.txt file, then python does not want to perceive the content normally. For generate random text i use lorem_text.
**In file:**
Veniam adipisci tempora explicabo natus atque eius architecto dignissimos, praesentium ad odio eligendi eum voluptate vero alias id?
**In console:**
Veniam вЃЎвЂЌвЂЊвЂЌвЃ¤вЃЎвЃЎвЃЎвЂЊвЃЎвЃўвЃЎвЂЊвЂЌвЃЈвЃЈвЃЈвЃўвЃЎвЂЌвЃЈвЂЌвЃЎвЃўвЂЌвЂЌвЃЎвЃ¤вЂЊвЂЌвЂЌвЃўвЃЎвЂЊвЃЎвЂЊвЃ¤вЃЎвЃЎadipisci tempora explicabo natus atque eius architecto dignissimos, praesentium ad odio eligendi eum voluptate vero alias id?
How I can get the text in normal form?

**Comment by AK5123** [comment]
@zentkhv I see that you have tried to embed secret into a cover message. Stegcloak uses invisible characters(zero_width_characters) for the embedding process and these characters are not invisible in certain places(it is visible in cmd, terminals etc). To get the text in normal form avoid printing the content in the console rather copy to your clipboard. 

If using the Stegcloak CLI tool,  it saves the content to your clipboard by default or you can write it to any file. 

To understand how stegcloak works please refer to this [link](https://blog.bitsrc.io/how-to-hide-secrets-in-strings-modern-text-hiding-in-javascript-613a9faa5787)

**Comment by zentkhv** [comment]
@AK5123 Thank you! After I started working directly with the clipboard without using a file, everything began to work correctly.
P.S. Perhaps it will be useful to someone. To work with the clipboard, I used:
import pyperclip
data = pyperclip.paste()
