### ISSUE TITLE
Improve docs on cli usage

### ISSUE THREAD

**Issue by mburszley** [KuroLabs/stegcloak#8]
Logically you can figure out some of the items are different parameter sets, but the docs don't make that clear.

What does cover mean here, the key/password?  I think it may be clearer to change the name.  Does it work to pass a file and a secret?  Probably not.  Are outputs on stdout or is it mandatory to specify output?

```
hide [options] [secret] [cover]

-f, --file <file>       Extract input from file
-n, --nocrypt           If you don't need encryption (default: false)
-i, --integrity         If additional security of preventing tampering is needed (default: false)
-o, --output <output>   Stream the results to an output file
-h, --help              display help for command
```

Similar questions here, where do you pass `[cover]` here to decrypt the string?  Options aren't stated in the same format as the previous example.

```
reveal [data]

-f, --file <file>       Extract input from file
-cp, --clip             Copy Data directly from clipboard
-o, --output <output>   Stream the secret to an output file
-h, --help              display help for command
```

**Comment by mohanpierce99** [comment]
Config is added along with samples and docs have been updated to achieve better readability.

The issue has been resolved, thus closing it +1
