### ISSUE TITLE
Add a `—config` option to the CLI tool

### ISSUE THREAD

**Issue by nandahkrishna** [KuroLabs/stegcloak#9]
As discussed in #8, we should add a `--config` option in case people want to use StegCloak in languages other than Node - the current interactive nature of the CLI tool is a problem in those cases.

**Comment by mohanpierce99** [comment]
@mburszley Thanks for the suggestion. Config file support is now [added](https://github.com/KuroLabs/stegcloak/wiki/Stegcloak---configuration-file). Along with this,env variable for the password is also included. Since it's meaningful to use environment variables only for the same.
